// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EKey_T int32

const (
	EKey_Invalid EKey_T = 0
	// login
	EKey_ReqLogin       EKey_T = 1
	EKey_RspLogin       EKey_T = 2
	EKey_ReqCreateRole  EKey_T = 3
	EKey_RspCreateRole  EKey_T = 4
	EKey_ReqLoginRole   EKey_T = 5
	EKey_RspLoginRole   EKey_T = 6     // 登录角色返回
	EKey_ReqPing        EKey_T = 100   // 心跳
	EKey_RspPing        EKey_T = 101   // 心跳
	EKey_ReqPingZZZ     EKey_T = 102   // 心跳(客户端切换后台发送该消息)
	EKey_RspPingZZZ     EKey_T = 103   // 心跳(客户端切换后台发送该消息)
	EKey_ReqEnterZone   EKey_T = 200   // 请求进入场景
	EKey_RspEnterZone   EKey_T = 201   // 响应进入场景
	EKey_ReqMove        EKey_T = 300   // 移动
	EKey_RspMove        EKey_T = 301   // 响应移动
	EKey_DspLogin       EKey_T = 10000 // 同步玩家登录数据
	EKey_DspSrvMaintain EKey_T = 10001 // 同步服务器维护
	EKey_DspKickRole    EKey_T = 10002 // 同步玩家踢下线
	EKey_DspEnterZone   EKey_T = 10003 // 准备进入场景
	EKey_DspMove        EKey_T = 33005 // 同步玩家移动
	// 0xF000 及以上为服务器保留用
	EKey_Max EKey_T = 65535
)

// Enum value maps for EKey_T.
var (
	EKey_T_name = map[int32]string{
		0:     "Invalid",
		1:     "ReqLogin",
		2:     "RspLogin",
		3:     "ReqCreateRole",
		4:     "RspCreateRole",
		5:     "ReqLoginRole",
		6:     "RspLoginRole",
		100:   "ReqPing",
		101:   "RspPing",
		102:   "ReqPingZZZ",
		103:   "RspPingZZZ",
		200:   "ReqEnterZone",
		201:   "RspEnterZone",
		300:   "ReqMove",
		301:   "RspMove",
		10000: "DspLogin",
		10001: "DspSrvMaintain",
		10002: "DspKickRole",
		10003: "DspEnterZone",
		33005: "DspMove",
		65535: "Max",
	}
	EKey_T_value = map[string]int32{
		"Invalid":        0,
		"ReqLogin":       1,
		"RspLogin":       2,
		"ReqCreateRole":  3,
		"RspCreateRole":  4,
		"ReqLoginRole":   5,
		"RspLoginRole":   6,
		"ReqPing":        100,
		"RspPing":        101,
		"ReqPingZZZ":     102,
		"RspPingZZZ":     103,
		"ReqEnterZone":   200,
		"RspEnterZone":   201,
		"ReqMove":        300,
		"RspMove":        301,
		"DspLogin":       10000,
		"DspSrvMaintain": 10001,
		"DspKickRole":    10002,
		"DspEnterZone":   10003,
		"DspMove":        33005,
		"Max":            65535,
	}
)

func (x EKey_T) Enum() *EKey_T {
	p := new(EKey_T)
	*p = x
	return p
}

func (x EKey_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EKey_T) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_enumTypes[0].Descriptor()
}

func (EKey_T) Type() protoreflect.EnumType {
	return &file_cmd_proto_enumTypes[0]
}

func (x EKey_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EKey_T.Descriptor instead.
func (EKey_T) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{0, 0}
}

type EKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKey) Reset() {
	*x = EKey{}
	mi := &file_cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKey) ProtoMessage() {}

func (x *EKey) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKey.ProtoReflect.Descriptor instead.
func (*EKey) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{0}
}

var File_cmd_proto protoreflect.FileDescriptor

const file_cmd_proto_rawDesc = "" +
	"\n" +
	"\tcmd.proto\x12\x02pb\"\xde\x02\n" +
	"\x04EKey\"\xd5\x02\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\x12\f\n" +
	"\bReqLogin\x10\x01\x12\f\n" +
	"\bRspLogin\x10\x02\x12\x11\n" +
	"\rReqCreateRole\x10\x03\x12\x11\n" +
	"\rRspCreateRole\x10\x04\x12\x10\n" +
	"\fReqLoginRole\x10\x05\x12\x10\n" +
	"\fRspLoginRole\x10\x06\x12\v\n" +
	"\aReqPing\x10d\x12\v\n" +
	"\aRspPing\x10e\x12\x0e\n" +
	"\n" +
	"ReqPingZZZ\x10f\x12\x0e\n" +
	"\n" +
	"RspPingZZZ\x10g\x12\x11\n" +
	"\fReqEnterZone\x10\xc8\x01\x12\x11\n" +
	"\fRspEnterZone\x10\xc9\x01\x12\f\n" +
	"\aReqMove\x10\xac\x02\x12\f\n" +
	"\aRspMove\x10\xad\x02\x12\r\n" +
	"\bDspLogin\x10\x90N\x12\x13\n" +
	"\x0eDspSrvMaintain\x10\x91N\x12\x10\n" +
	"\vDspKickRole\x10\x92N\x12\x11\n" +
	"\fDspEnterZone\x10\x93N\x12\r\n" +
	"\aDspMove\x10\xed\x81\x02\x12\t\n" +
	"\x03Max\x10\xff\xff\x03B\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_proto_rawDescOnce sync.Once
	file_cmd_proto_rawDescData []byte
)

func file_cmd_proto_rawDescGZIP() []byte {
	file_cmd_proto_rawDescOnce.Do(func() {
		file_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_rawDesc), len(file_cmd_proto_rawDesc)))
	})
	return file_cmd_proto_rawDescData
}

var file_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_proto_goTypes = []any{
	(EKey_T)(0),  // 0: pb.EKey.T
	(*EKey)(nil), // 1: pb.EKey
}
var file_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_init() }
func file_cmd_proto_init() {
	if File_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_rawDesc), len(file_cmd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_goTypes,
		DependencyIndexes: file_cmd_proto_depIdxs,
		EnumInfos:         file_cmd_proto_enumTypes,
		MessageInfos:      file_cmd_proto_msgTypes,
	}.Build()
	File_cmd_proto = out.File
	file_cmd_proto_goTypes = nil
	file_cmd_proto_depIdxs = nil
}
