// Code generated by pbgen. DO NOT EDIT.
// source: cmd.proto, cmd_req.proto, cmd_rsp.proto, cmd_dsp.proto

package pb

import (
	"encoding/binary"
	"errors"

	"google.golang.org/protobuf/proto"
)

var _parser = NewParser()

func init() {
	_parser.Load()
}

type message interface {
	proto.Message

	Key() EKey_T
}

type Package struct {
	msg   message
	err   EErrorCode_T
	bytes []byte
}

func NewPackage(msg proto.Message, errs ...EErrorCode_T) *Package {
	err := EErrorCode_Ok
	if len(errs) != 0 {
		err = errs[0]
	}
	return &Package{
		msg: msg.(message),
		err: err,
	}
}

func (p *Package) Key() EKey_T {
	return p.msg.Key()
}

func (p *Package) Marshal() ([]byte, error) {
	if len(p.bytes) != 0 {
		return p.bytes, nil
	}

	if p.msg == nil {
		return nil, errors.New("message is nil")
	}

	bytes := make([]byte, 4, 8)

	binary.LittleEndian.PutUint16(bytes[0:], uint16(p.msg.Key()))
	binary.LittleEndian.PutUint16(bytes[2:], uint16(p.err))

	if p.err != EErrorCode_Ok {
		return bytes, nil
	}

	body, marshalErr := proto.Marshal(p.msg)
	if marshalErr != nil {
		return nil, marshalErr
	}

	bodyLen := uint32(len(body))
	bytes = append(bytes, 0, 0, 0, 0)
	binary.LittleEndian.PutUint32(bytes[4:], bodyLen)
	bytes = append(bytes, body...)
	p.bytes = bytes

	return bytes, nil
}

func Unmarshal(key EKey_T, data []byte) proto.Message {
	return _parser.Unmarshal(key, data)
}

// parser handles protobuf message parsing by EKey
type parser struct {
	types map[EKey_T]func() proto.Message
}

// NewParser creates a new Parser instance
func NewParser() *parser {
	return &parser{
		types: make(map[EKey_T]func() proto.Message),
	}
}

// Register registers a message factory for a given EKey
func (p *parser) Register(key EKey_T, factory func() proto.Message) {
	p.types[key] = factory
}

// New creates a new message instance for the given EKey
func (p *parser) New(key EKey_T) proto.Message {
	factory, ok := p.types[key]
	if !ok {
		return nil
	}
	return factory()
}

// Unmarshal unmarshals binary data into a new message instance
func (p *parser) Unmarshal(key EKey_T, data []byte) proto.Message {
	msg := p.New(key)
	if msg == nil {
		return nil
	}
	if err := proto.Unmarshal(data, msg); err != nil {
		return nil
	}
	return msg
}

// Load registers all message types
func (p *parser) Load() {
	p.Register(EKey_ReqLogin, func() proto.Message { return &ReqLogin{} })
	p.Register(EKey_ReqCreateRole, func() proto.Message { return &ReqCreateRole{} })
	p.Register(EKey_ReqLoginRole, func() proto.Message { return &ReqLoginRole{} })
	p.Register(EKey_ReqPing, func() proto.Message { return &ReqPing{} })
	p.Register(EKey_ReqPingZZZ, func() proto.Message { return &ReqPingZZZ{} })
	p.Register(EKey_ReqEnterZone, func() proto.Message { return &ReqEnterZone{} })
	p.Register(EKey_ReqMove, func() proto.Message { return &ReqMove{} })
	p.Register(EKey_RspLogin, func() proto.Message { return &RspLogin{} })
	p.Register(EKey_RspCreateRole, func() proto.Message { return &RspCreateRole{} })
	p.Register(EKey_RspLoginRole, func() proto.Message { return &RspLoginRole{} })
	p.Register(EKey_RspPing, func() proto.Message { return &RspPing{} })
	p.Register(EKey_RspPingZZZ, func() proto.Message { return &RspPingZZZ{} })
	p.Register(EKey_RspEnterZone, func() proto.Message { return &RspEnterZone{} })
	p.Register(EKey_RspMove, func() proto.Message { return &RspMove{} })
	p.Register(EKey_DspLogin, func() proto.Message { return &DspLogin{} })
	p.Register(EKey_DspSrvMaintain, func() proto.Message { return &DspSrvMaintain{} })
	p.Register(EKey_DspKickRole, func() proto.Message { return &DspKickRole{} })
	p.Register(EKey_DspMove, func() proto.Message { return &DspMove{} })
}

func (msg *ReqLogin) Key() EKey_T {
	return EKey_ReqLogin
}

func (msg *ReqLogin) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *ReqCreateRole) Key() EKey_T {
	return EKey_ReqCreateRole
}

func (msg *ReqCreateRole) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *ReqLoginRole) Key() EKey_T {
	return EKey_ReqLoginRole
}

func (msg *ReqLoginRole) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *ReqPing) Key() EKey_T {
	return EKey_ReqPing
}

func (msg *ReqPing) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *ReqPingZZZ) Key() EKey_T {
	return EKey_ReqPingZZZ
}

func (msg *ReqPingZZZ) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *ReqEnterZone) Key() EKey_T {
	return EKey_ReqEnterZone
}

func (msg *ReqEnterZone) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *ReqMove) Key() EKey_T {
	return EKey_ReqMove
}

func (msg *ReqMove) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspLogin) Key() EKey_T {
	return EKey_RspLogin
}

func (msg *RspLogin) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspCreateRole) Key() EKey_T {
	return EKey_RspCreateRole
}

func (msg *RspCreateRole) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspLoginRole) Key() EKey_T {
	return EKey_RspLoginRole
}

func (msg *RspLoginRole) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspPing) Key() EKey_T {
	return EKey_RspPing
}

func (msg *RspPing) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspPingZZZ) Key() EKey_T {
	return EKey_RspPingZZZ
}

func (msg *RspPingZZZ) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspEnterZone) Key() EKey_T {
	return EKey_RspEnterZone
}

func (msg *RspEnterZone) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *RspMove) Key() EKey_T {
	return EKey_RspMove
}

func (msg *RspMove) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *DspLogin) Key() EKey_T {
	return EKey_DspLogin
}

func (msg *DspLogin) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *DspSrvMaintain) Key() EKey_T {
	return EKey_DspSrvMaintain
}

func (msg *DspSrvMaintain) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *DspKickRole) Key() EKey_T {
	return EKey_DspKickRole
}

func (msg *DspKickRole) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

func (msg *DspMove) Key() EKey_T {
	return EKey_DspMove
}

func (msg *DspMove) Marshal() ([]byte, error) {
	return proto.Marshal(msg)
}

