// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd_dsp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DspLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LoginData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 登录必要数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspLogin) Reset() {
	*x = DspLogin{}
	mi := &file_cmd_dsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspLogin) ProtoMessage() {}

func (x *DspLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspLogin.ProtoReflect.Descriptor instead.
func (*DspLogin) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{0}
}

func (x *DspLogin) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务器维护
type DspSrvMaintain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RebootTime    int64                  `protobuf:"zigzag64,1,opt,name=reboot_time,json=rebootTime,proto3" json:"reboot_time,omitempty"`       // 预计开服时间戳，为 0 代表未知
	ShutdownTime  int64                  `protobuf:"zigzag64,2,opt,name=shutdown_time,json=shutdownTime,proto3" json:"shutdown_time,omitempty"` // 关服时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspSrvMaintain) Reset() {
	*x = DspSrvMaintain{}
	mi := &file_cmd_dsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspSrvMaintain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspSrvMaintain) ProtoMessage() {}

func (x *DspSrvMaintain) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspSrvMaintain.ProtoReflect.Descriptor instead.
func (*DspSrvMaintain) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{1}
}

func (x *DspSrvMaintain) GetRebootTime() int64 {
	if x != nil {
		return x.RebootTime
	}
	return 0
}

func (x *DspSrvMaintain) GetShutdownTime() int64 {
	if x != nil {
		return x.ShutdownTime
	}
	return 0
}

// 踢玩家下线
type DspKickRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            EKickType_T            `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.EKickType_T" json:"ty,omitempty"`     // 踢下线类型
	SessId        int64                  `protobuf:"zigzag64,2,opt,name=sess_id,json=sessId,proto3" json:"sess_id,omitempty"` // sess id，服务器使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspKickRole) Reset() {
	*x = DspKickRole{}
	mi := &file_cmd_dsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspKickRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspKickRole) ProtoMessage() {}

func (x *DspKickRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspKickRole.ProtoReflect.Descriptor instead.
func (*DspKickRole) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{2}
}

func (x *DspKickRole) GetTy() EKickType_T {
	if x != nil {
		return x.Ty
	}
	return EKickType_Invalid
}

func (x *DspKickRole) GetSessId() int64 {
	if x != nil {
		return x.SessId
	}
	return 0
}

// 准备进入场景
type DspEnterZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspEnterZone) Reset() {
	*x = DspEnterZone{}
	mi := &file_cmd_dsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspEnterZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspEnterZone) ProtoMessage() {}

func (x *DspEnterZone) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspEnterZone.ProtoReflect.Descriptor instead.
func (*DspEnterZone) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{3}
}

type DspMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色id
	Pos           *Vector                `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`                      // 位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspMove) Reset() {
	*x = DspMove{}
	mi := &file_cmd_dsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspMove) ProtoMessage() {}

func (x *DspMove) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspMove.ProtoReflect.Descriptor instead.
func (*DspMove) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{4}
}

func (x *DspMove) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DspMove) GetPos() *Vector {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_cmd_dsp_proto protoreflect.FileDescriptor

const file_cmd_dsp_proto_rawDesc = "" +
	"\n" +
	"\rcmd_dsp.proto\x12\x02pb\x1a\n" +
	"data.proto\x1a\n" +
	"enum.proto\"-\n" +
	"\bDspLogin\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.pb.LoginDataR\x04data\"V\n" +
	"\x0eDspSrvMaintain\x12\x1f\n" +
	"\vreboot_time\x18\x01 \x01(\x12R\n" +
	"rebootTime\x12#\n" +
	"\rshutdown_time\x18\x02 \x01(\x12R\fshutdownTime\"G\n" +
	"\vDspKickRole\x12\x1f\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x0f.pb.EKickType.TR\x02ty\x12\x17\n" +
	"\asess_id\x18\x02 \x01(\x12R\x06sessId\"\x0e\n" +
	"\fDspEnterZone\"@\n" +
	"\aDspMove\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1c\n" +
	"\x03pos\x18\x02 \x01(\v2\n" +
	".pb.VectorR\x03posB\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_dsp_proto_rawDescOnce sync.Once
	file_cmd_dsp_proto_rawDescData []byte
)

func file_cmd_dsp_proto_rawDescGZIP() []byte {
	file_cmd_dsp_proto_rawDescOnce.Do(func() {
		file_cmd_dsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_dsp_proto_rawDesc), len(file_cmd_dsp_proto_rawDesc)))
	})
	return file_cmd_dsp_proto_rawDescData
}

var file_cmd_dsp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cmd_dsp_proto_goTypes = []any{
	(*DspLogin)(nil),       // 0: pb.DspLogin
	(*DspSrvMaintain)(nil), // 1: pb.DspSrvMaintain
	(*DspKickRole)(nil),    // 2: pb.DspKickRole
	(*DspEnterZone)(nil),   // 3: pb.DspEnterZone
	(*DspMove)(nil),        // 4: pb.DspMove
	(*LoginData)(nil),      // 5: pb.LoginData
	(EKickType_T)(0),       // 6: pb.EKickType.T
	(*Vector)(nil),         // 7: pb.Vector
}
var file_cmd_dsp_proto_depIdxs = []int32{
	5, // 0: pb.DspLogin.data:type_name -> pb.LoginData
	6, // 1: pb.DspKickRole.ty:type_name -> pb.EKickType.T
	7, // 2: pb.DspMove.pos:type_name -> pb.Vector
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cmd_dsp_proto_init() }
func file_cmd_dsp_proto_init() {
	if File_cmd_dsp_proto != nil {
		return
	}
	file_data_proto_init()
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_dsp_proto_rawDesc), len(file_cmd_dsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_dsp_proto_goTypes,
		DependencyIndexes: file_cmd_dsp_proto_depIdxs,
		MessageInfos:      file_cmd_dsp_proto_msgTypes,
	}.Build()
	File_cmd_dsp_proto = out.File
	file_cmd_dsp_proto_goTypes = nil
	file_cmd_dsp_proto_depIdxs = nil
}
