// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleSummaryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"zigzag64,1,opt,name=id,proto3" json:"id,omitempty"`                             // id
	Cid           int64                  `protobuf:"zigzag64,2,opt,name=cid,proto3" json:"cid,omitempty"`                           // 配置cid
	Lv            int64                  `protobuf:"zigzag64,3,opt,name=lv,proto3" json:"lv,omitempty"`                             // 等级
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                            // 角色名字
	Icon          int64                  `protobuf:"zigzag64,5,opt,name=icon,proto3" json:"icon,omitempty"`                         // 头像
	YoungTs       int64                  `protobuf:"zigzag64,6,opt,name=young_ts,json=youngTs,proto3" json:"young_ts,omitempty"`    // 当天累计防沉迷时间
	CreateTs      int64                  `protobuf:"zigzag64,7,opt,name=create_ts,json=createTs,proto3" json:"create_ts,omitempty"` // 创角时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSummaryData) Reset() {
	*x = RoleSummaryData{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSummaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSummaryData) ProtoMessage() {}

func (x *RoleSummaryData) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSummaryData.ProtoReflect.Descriptor instead.
func (*RoleSummaryData) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *RoleSummaryData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleSummaryData) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RoleSummaryData) GetLv() int64 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *RoleSummaryData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleSummaryData) GetIcon() int64 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *RoleSummaryData) GetYoungTs() int64 {
	if x != nil {
		return x.YoungTs
	}
	return 0
}

func (x *RoleSummaryData) GetCreateTs() int64 {
	if x != nil {
		return x.CreateTs
	}
	return 0
}

// 登陆必要数据
type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regain        bool                   `protobuf:"varint,1,opt,name=regain,proto3" json:"regain,omitempty"` // true-有可以找回的资源
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *LoginData) GetRegain() bool {
	if x != nil {
		return x.Regain
	}
	return false
}

type Award struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Batch         int64                  `protobuf:"zigzag64,1,opt,name=batch,proto3" json:"batch,omitempty"`
	Bind          int64                  `protobuf:"zigzag64,2,opt,name=bind,proto3" json:"bind,omitempty"`
	Weight        int64                  `protobuf:"zigzag64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Job           int64                  `protobuf:"zigzag64,4,opt,name=job,proto3" json:"job,omitempty"`
	Due           int64                  `protobuf:"zigzag64,6,opt,name=due,proto3" json:"due,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Award) Reset() {
	*x = Award{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Award) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Award) ProtoMessage() {}

func (x *Award) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Award.ProtoReflect.Descriptor instead.
func (*Award) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *Award) GetBatch() int64 {
	if x != nil {
		return x.Batch
	}
	return 0
}

func (x *Award) GetBind() int64 {
	if x != nil {
		return x.Bind
	}
	return 0
}

func (x *Award) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Award) GetJob() int64 {
	if x != nil {
		return x.Job
	}
	return 0
}

func (x *Award) GetDue() int64 {
	if x != nil {
		return x.Due
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           int64                  `protobuf:"zigzag64,1,opt,name=idx,proto3" json:"idx,omitempty"`     // 编号
	Id            int64                  `protobuf:"zigzag64,2,opt,name=id,proto3" json:"id,omitempty"`       // 唯一id
	Cid           int64                  `protobuf:"zigzag64,3,opt,name=cid,proto3" json:"cid,omitempty"`     // 配置id
	Count         int64                  `protobuf:"zigzag64,4,opt,name=count,proto3" json:"count,omitempty"` // 数量
	Bind          int64                  `protobuf:"zigzag64,5,opt,name=bind,proto3" json:"bind,omitempty"`   // 是否绑定 0-非绑定，1-绑定
	Due           int64                  `protobuf:"zigzag64,6,opt,name=due,proto3" json:"due,omitempty"`     // 有效时间 0 为无限期
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetIdx() int64 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *Item) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetBind() int64 {
	if x != nil {
		return x.Bind
	}
	return 0
}

func (x *Item) GetDue() int64 {
	if x != nil {
		return x.Due
	}
	return 0
}

type Attr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            EAttrType_T            `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.EAttrType_T" json:"ty,omitempty"` // 类型
	Val           int64                  `protobuf:"zigzag64,2,opt,name=val,proto3" json:"val,omitempty"`                 // 值
	Rate          int64                  `protobuf:"zigzag64,3,opt,name=rate,proto3" json:"rate,omitempty"`               // 比率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attr) Reset() {
	*x = Attr{}
	mi := &file_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{4}
}

func (x *Attr) GetTy() EAttrType_T {
	if x != nil {
		return x.Ty
	}
	return EAttrType_Invalid
}

func (x *Attr) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *Attr) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             int64                  `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{5}
}

func (x *Vector) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector) GetZ() int64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\x02pb\x1a\n" +
	"enum.proto\"\xa3\x01\n" +
	"\x0fRoleSummaryData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x12R\x02id\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x12R\x03cid\x12\x0e\n" +
	"\x02lv\x18\x03 \x01(\x12R\x02lv\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\x12R\x04icon\x12\x19\n" +
	"\byoung_ts\x18\x06 \x01(\x12R\ayoungTs\x12\x1b\n" +
	"\tcreate_ts\x18\a \x01(\x12R\bcreateTs\"#\n" +
	"\tLoginData\x12\x16\n" +
	"\x06regain\x18\x01 \x01(\bR\x06regain\"m\n" +
	"\x05Award\x12\x14\n" +
	"\x05batch\x18\x01 \x01(\x12R\x05batch\x12\x12\n" +
	"\x04bind\x18\x02 \x01(\x12R\x04bind\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x12R\x06weight\x12\x10\n" +
	"\x03job\x18\x04 \x01(\x12R\x03job\x12\x10\n" +
	"\x03due\x18\x06 \x01(\x12R\x03due\"v\n" +
	"\x04Item\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x12R\x03idx\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x12R\x02id\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\x12R\x03cid\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x12R\x05count\x12\x12\n" +
	"\x04bind\x18\x05 \x01(\x12R\x04bind\x12\x10\n" +
	"\x03due\x18\x06 \x01(\x12R\x03due\"M\n" +
	"\x04Attr\x12\x1f\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x0f.pb.EAttrType.TR\x02ty\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x12R\x03val\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x12R\x04rate\"2\n" +
	"\x06Vector\x12\f\n" +
	"\x01x\x18\x01 \x01(\x03R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x03R\x01zB\vZ\tserver/pbb\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_data_proto_goTypes = []any{
	(*RoleSummaryData)(nil), // 0: pb.RoleSummaryData
	(*LoginData)(nil),       // 1: pb.LoginData
	(*Award)(nil),           // 2: pb.Award
	(*Item)(nil),            // 3: pb.Item
	(*Attr)(nil),            // 4: pb.Attr
	(*Vector)(nil),          // 5: pb.Vector
	(EAttrType_T)(0),        // 6: pb.EAttrType.T
}
var file_data_proto_depIdxs = []int32{
	6, // 0: pb.Attr.ty:type_name -> pb.EAttrType.T
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
