// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EKey_T int32

const (
	EKey_Invalid EKey_T = 0
	// login
	EKey_Login      EKey_T = 1
	EKey_CreateRole EKey_T = 2
	EKey_LoginRole  EKey_T = 4
	EKey_Ping       EKey_T = 10 // 心跳
	EKey_PingXXX    EKey_T = 11 // 心跳(客户端切换后台发送该消息)
	EKey_EnterZone  EKey_T = 20 // 通知服务器已经进入场景
	EKey_Move       EKey_T = 21 // 移动
	// dsp start
	EKey_SyncBegin         EKey_T = 32768 // 所有的同步消息的起始值
	EKey_LoginFast         EKey_T = 33000 // 同步快速重登 token
	EKey_LoginData         EKey_T = 33001 // 同步玩家登录数据
	EKey_ServerMaintain    EKey_T = 33002 // 同步玩家登录数据
	EKey_KickRole          EKey_T = 33003 // 踢玩家下线
	EKey_PreparedEnterZone EKey_T = 33004 // 准备进入场景
	EKey_SyncMove          EKey_T = 33005 // 同步玩家移动
	EKey_SyncEnd           EKey_T = 49151 // 同步消息的结束值
	// 0xF000 及以上为服务器保留用
	EKey_Max EKey_T = 65535
)

// Enum value maps for EKey_T.
var (
	EKey_T_name = map[int32]string{
		0:     "Invalid",
		1:     "Login",
		2:     "CreateRole",
		4:     "LoginRole",
		10:    "Ping",
		11:    "PingXXX",
		20:    "EnterZone",
		21:    "Move",
		32768: "SyncBegin",
		33000: "LoginFast",
		33001: "LoginData",
		33002: "ServerMaintain",
		33003: "KickRole",
		33004: "PreparedEnterZone",
		33005: "SyncMove",
		49151: "SyncEnd",
		65535: "Max",
	}
	EKey_T_value = map[string]int32{
		"Invalid":           0,
		"Login":             1,
		"CreateRole":        2,
		"LoginRole":         4,
		"Ping":              10,
		"PingXXX":           11,
		"EnterZone":         20,
		"Move":              21,
		"SyncBegin":         32768,
		"LoginFast":         33000,
		"LoginData":         33001,
		"ServerMaintain":    33002,
		"KickRole":          33003,
		"PreparedEnterZone": 33004,
		"SyncMove":          33005,
		"SyncEnd":           49151,
		"Max":               65535,
	}
)

func (x EKey_T) Enum() *EKey_T {
	p := new(EKey_T)
	*p = x
	return p
}

func (x EKey_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EKey_T) Descriptor() protoreflect.EnumDescriptor {
	return file_cmd_proto_enumTypes[0].Descriptor()
}

func (EKey_T) Type() protoreflect.EnumType {
	return &file_cmd_proto_enumTypes[0]
}

func (x EKey_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EKey_T.Descriptor instead.
func (EKey_T) EnumDescriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{0, 0}
}

type EKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKey) Reset() {
	*x = EKey{}
	mi := &file_cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKey) ProtoMessage() {}

func (x *EKey) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKey.ProtoReflect.Descriptor instead.
func (*EKey) Descriptor() ([]byte, []int) {
	return file_cmd_proto_rawDescGZIP(), []int{0}
}

var File_cmd_proto protoreflect.FileDescriptor

const file_cmd_proto_rawDesc = "" +
	"\n" +
	"\tcmd.proto\x12\x02pb\"\x8f\x02\n" +
	"\x04EKey\"\x86\x02\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\x12\t\n" +
	"\x05Login\x10\x01\x12\x0e\n" +
	"\n" +
	"CreateRole\x10\x02\x12\r\n" +
	"\tLoginRole\x10\x04\x12\b\n" +
	"\x04Ping\x10\n" +
	"\x12\v\n" +
	"\aPingXXX\x10\v\x12\r\n" +
	"\tEnterZone\x10\x14\x12\b\n" +
	"\x04Move\x10\x15\x12\x0f\n" +
	"\tSyncBegin\x10\x80\x80\x02\x12\x0f\n" +
	"\tLoginFast\x10\xe8\x81\x02\x12\x0f\n" +
	"\tLoginData\x10\xe9\x81\x02\x12\x14\n" +
	"\x0eServerMaintain\x10\xea\x81\x02\x12\x0e\n" +
	"\bKickRole\x10\xeb\x81\x02\x12\x17\n" +
	"\x11PreparedEnterZone\x10\xec\x81\x02\x12\x0e\n" +
	"\bSyncMove\x10\xed\x81\x02\x12\r\n" +
	"\aSyncEnd\x10\xff\xff\x02\x12\t\n" +
	"\x03Max\x10\xff\xff\x03B\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_proto_rawDescOnce sync.Once
	file_cmd_proto_rawDescData []byte
)

func file_cmd_proto_rawDescGZIP() []byte {
	file_cmd_proto_rawDescOnce.Do(func() {
		file_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_rawDesc), len(file_cmd_proto_rawDesc)))
	})
	return file_cmd_proto_rawDescData
}

var file_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cmd_proto_goTypes = []any{
	(EKey_T)(0),  // 0: pb.EKey.T
	(*EKey)(nil), // 1: pb.EKey
}
var file_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_proto_init() }
func file_cmd_proto_init() {
	if File_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_rawDesc), len(file_cmd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_proto_goTypes,
		DependencyIndexes: file_cmd_proto_depIdxs,
		EnumInfos:         file_cmd_proto_enumTypes,
		MessageInfos:      file_cmd_proto_msgTypes,
	}.Build()
	File_cmd_proto = out.File
	file_cmd_proto_goTypes = nil
	file_cmd_proto_depIdxs = nil
}
