// Code generated by pbgen. DO NOT EDIT.
// source: cmd.proto, cmd_req.proto, cmd_rsp.proto, cmd_dsp.proto

package pb

import (
	"google.golang.org/protobuf/proto"
)

var _parser = NewParser()

func init() {
	_parser.Load()
}

func Unmarshal(key EKey_T, data []byte) proto.Message {
	return _parser.Unmarshal(key, data)
}

// parser handles protobuf message parsing by EKey
type parser struct {
	types map[EKey_T]func() proto.Message
}

// NewParser creates a new Parser instance
func NewParser() *parser {
	return &parser{
		types: make(map[EKey_T]func() proto.Message),
	}
}

// Register registers a message factory for a given EKey
func (p *parser) Register(key EKey_T, factory func() proto.Message) {
	p.types[key] = factory
}

// New creates a new message instance for the given EKey
func (p *parser) New(key EKey_T) proto.Message {
	factory, ok := p.types[key]
	if !ok {
		return nil
	}
	return factory()
}

// Unmarshal unmarshals binary data into a new message instance
func (p *parser) Unmarshal(key EKey_T, data []byte) proto.Message {
	msg := p.New(key)
	if msg == nil {
		return nil
	}
	if err := proto.Unmarshal(data, msg); err != nil {
		return nil
	}
	return msg
}

// Load registers all message types
func (p *parser) Load() {
	p.Register(EKey_Login, func() proto.Message { return &ReqLogin{} })
	p.Register(EKey_CreateRole, func() proto.Message { return &ReqCreateRole{} })
	p.Register(EKey_DeleteRole, func() proto.Message { return &ReqDeleteRole{} })
	p.Register(EKey_LoginRole, func() proto.Message { return &ReqLoginRole{} })
	p.Register(EKey_Ping, func() proto.Message { return &ReqPing{} })
	p.Register(EKey_PingXXX, func() proto.Message { return &ReqPingXXX{} })
	p.Register(EKey_EnterScene, func() proto.Message { return &ReqEnterScene{} })
	p.Register(EKey_TestEnter, func() proto.Message { return &ReqTestEnter{} })
	p.Register(EKey_Login, func() proto.Message { return &RspLogin{} })
	p.Register(EKey_CreateRole, func() proto.Message { return &RspCreateRole{} })
	p.Register(EKey_DeleteRole, func() proto.Message { return &RspDeleteRole{} })
	p.Register(EKey_LoginRole, func() proto.Message { return &RspLoginRole{} })
	p.Register(EKey_Ping, func() proto.Message { return &RspPing{} })
	p.Register(EKey_PingXXX, func() proto.Message { return &RspPingXXX{} })
	p.Register(EKey_EnterScene, func() proto.Message { return &RspEnterScene{} })
	p.Register(EKey_TestEnter, func() proto.Message { return &RspTestEnter{} })
	p.Register(EKey_LoginFast, func() proto.Message { return &DspLoginFast{} })
	p.Register(EKey_LoginData, func() proto.Message { return &DspLoginData{} })
	p.Register(EKey_ServerMaintain, func() proto.Message { return &DspServerMaintain{} })
	p.Register(EKey_KickRole, func() proto.Message { return &DspKickRole{} })
	p.Register(EKey_PreparedEnterScene, func() proto.Message { return &DspPreparedEnterScene{} })
	p.Register(EKey_Test, func() proto.Message { return &DspTest{} })
}

func (msg *ReqLogin) Key() EKey_T {
	return EKey_Login
}

func (msg *ReqCreateRole) Key() EKey_T {
	return EKey_CreateRole
}

func (msg *ReqDeleteRole) Key() EKey_T {
	return EKey_DeleteRole
}

func (msg *ReqLoginRole) Key() EKey_T {
	return EKey_LoginRole
}

func (msg *ReqPing) Key() EKey_T {
	return EKey_Ping
}

func (msg *ReqPingXXX) Key() EKey_T {
	return EKey_PingXXX
}

func (msg *ReqEnterScene) Key() EKey_T {
	return EKey_EnterScene
}

func (msg *ReqTestEnter) Key() EKey_T {
	return EKey_TestEnter
}

func (msg *RspLogin) Key() EKey_T {
	return EKey_Login
}

func (msg *RspCreateRole) Key() EKey_T {
	return EKey_CreateRole
}

func (msg *RspDeleteRole) Key() EKey_T {
	return EKey_DeleteRole
}

func (msg *RspLoginRole) Key() EKey_T {
	return EKey_LoginRole
}

func (msg *RspPing) Key() EKey_T {
	return EKey_Ping
}

func (msg *RspPingXXX) Key() EKey_T {
	return EKey_PingXXX
}

func (msg *RspEnterScene) Key() EKey_T {
	return EKey_EnterScene
}

func (msg *RspTestEnter) Key() EKey_T {
	return EKey_TestEnter
}

func (msg *DspLoginFast) Key() EKey_T {
	return EKey_LoginFast
}

func (msg *DspLoginData) Key() EKey_T {
	return EKey_LoginData
}

func (msg *DspServerMaintain) Key() EKey_T {
	return EKey_ServerMaintain
}

func (msg *DspKickRole) Key() EKey_T {
	return EKey_KickRole
}

func (msg *DspPreparedEnterScene) Key() EKey_T {
	return EKey_PreparedEnterScene
}

func (msg *DspTest) Key() EKey_T {
	return EKey_Test
}

