// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd_dsp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /////////////////////////////////////////////////////////////////////
// 同步消息标记无实际业务内容，仅用于标记同步消息的开始和结束，方便服务器处理
type DspSyncBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspSyncBegin) Reset() {
	*x = DspSyncBegin{}
	mi := &file_cmd_dsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspSyncBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspSyncBegin) ProtoMessage() {}

func (x *DspSyncBegin) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspSyncBegin.ProtoReflect.Descriptor instead.
func (*DspSyncBegin) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{0}
}

type DspSyncEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspSyncEnd) Reset() {
	*x = DspSyncEnd{}
	mi := &file_cmd_dsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspSyncEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspSyncEnd) ProtoMessage() {}

func (x *DspSyncEnd) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspSyncEnd.ProtoReflect.Descriptor instead.
func (*DspSyncEnd) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{1}
}

// 同步快速重登 token
type DspLoginFast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            ESignInFastType_T      `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.ESignInFastType_T" json:"ty,omitempty"` // 可快速重登的类型
	Timestamp     int64                  `protobuf:"zigzag64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // 时间戳
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                      // token
	Magic         int64                  `protobuf:"zigzag64,4,opt,name=magic,proto3" json:"magic,omitempty"`                   // 魔数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspLoginFast) Reset() {
	*x = DspLoginFast{}
	mi := &file_cmd_dsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspLoginFast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspLoginFast) ProtoMessage() {}

func (x *DspLoginFast) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspLoginFast.ProtoReflect.Descriptor instead.
func (*DspLoginFast) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{2}
}

func (x *DspLoginFast) GetTy() ESignInFastType_T {
	if x != nil {
		return x.Ty
	}
	return ESignInFastType_Invalid
}

func (x *DspLoginFast) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DspLoginFast) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DspLoginFast) GetMagic() int64 {
	if x != nil {
		return x.Magic
	}
	return 0
}

type DspLoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LoginData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 登录必要数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspLoginData) Reset() {
	*x = DspLoginData{}
	mi := &file_cmd_dsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspLoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspLoginData) ProtoMessage() {}

func (x *DspLoginData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspLoginData.ProtoReflect.Descriptor instead.
func (*DspLoginData) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{3}
}

func (x *DspLoginData) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 服务器维护
type DspServerMaintain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RebootTime    int64                  `protobuf:"zigzag64,1,opt,name=reboot_time,json=rebootTime,proto3" json:"reboot_time,omitempty"`       // 预计开服时间戳，为 0 代表未知
	ShutdownTime  int64                  `protobuf:"zigzag64,2,opt,name=shutdown_time,json=shutdownTime,proto3" json:"shutdown_time,omitempty"` // 关服时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspServerMaintain) Reset() {
	*x = DspServerMaintain{}
	mi := &file_cmd_dsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspServerMaintain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspServerMaintain) ProtoMessage() {}

func (x *DspServerMaintain) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspServerMaintain.ProtoReflect.Descriptor instead.
func (*DspServerMaintain) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{4}
}

func (x *DspServerMaintain) GetRebootTime() int64 {
	if x != nil {
		return x.RebootTime
	}
	return 0
}

func (x *DspServerMaintain) GetShutdownTime() int64 {
	if x != nil {
		return x.ShutdownTime
	}
	return 0
}

// 踢玩家下线
type DspKickRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            EKickType_T            `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.EKickType_T" json:"ty,omitempty"`     // 踢下线类型
	SessId        int64                  `protobuf:"zigzag64,2,opt,name=sess_id,json=sessId,proto3" json:"sess_id,omitempty"` // sess id，服务器使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspKickRole) Reset() {
	*x = DspKickRole{}
	mi := &file_cmd_dsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspKickRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspKickRole) ProtoMessage() {}

func (x *DspKickRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspKickRole.ProtoReflect.Descriptor instead.
func (*DspKickRole) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{5}
}

func (x *DspKickRole) GetTy() EKickType_T {
	if x != nil {
		return x.Ty
	}
	return EKickType_Invalid
}

func (x *DspKickRole) GetSessId() int64 {
	if x != nil {
		return x.SessId
	}
	return 0
}

// 更新邮件
type DspPreparedEnterZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspPreparedEnterZone) Reset() {
	*x = DspPreparedEnterZone{}
	mi := &file_cmd_dsp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspPreparedEnterZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspPreparedEnterZone) ProtoMessage() {}

func (x *DspPreparedEnterZone) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspPreparedEnterZone.ProtoReflect.Descriptor instead.
func (*DspPreparedEnterZone) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{6}
}

type DspSyncMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 角色id
	Pos           *Vector                `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`                      // 位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DspSyncMove) Reset() {
	*x = DspSyncMove{}
	mi := &file_cmd_dsp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DspSyncMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DspSyncMove) ProtoMessage() {}

func (x *DspSyncMove) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_dsp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DspSyncMove.ProtoReflect.Descriptor instead.
func (*DspSyncMove) Descriptor() ([]byte, []int) {
	return file_cmd_dsp_proto_rawDescGZIP(), []int{7}
}

func (x *DspSyncMove) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *DspSyncMove) GetPos() *Vector {
	if x != nil {
		return x.Pos
	}
	return nil
}

var File_cmd_dsp_proto protoreflect.FileDescriptor

const file_cmd_dsp_proto_rawDesc = "" +
	"\n" +
	"\rcmd_dsp.proto\x12\x02pb\x1a\n" +
	"data.proto\x1a\n" +
	"enum.proto\"\x0e\n" +
	"\fDspSyncBegin\"\f\n" +
	"\n" +
	"DspSyncEnd\"\x7f\n" +
	"\fDspLoginFast\x12%\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x15.pb.ESignInFastType.TR\x02ty\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x12R\ttimestamp\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x14\n" +
	"\x05magic\x18\x04 \x01(\x12R\x05magic\"1\n" +
	"\fDspLoginData\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.pb.LoginDataR\x04data\"Y\n" +
	"\x11DspServerMaintain\x12\x1f\n" +
	"\vreboot_time\x18\x01 \x01(\x12R\n" +
	"rebootTime\x12#\n" +
	"\rshutdown_time\x18\x02 \x01(\x12R\fshutdownTime\"G\n" +
	"\vDspKickRole\x12\x1f\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x0f.pb.EKickType.TR\x02ty\x12\x17\n" +
	"\asess_id\x18\x02 \x01(\x12R\x06sessId\"\x16\n" +
	"\x14DspPreparedEnterZone\"D\n" +
	"\vDspSyncMove\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1c\n" +
	"\x03pos\x18\x02 \x01(\v2\n" +
	".pb.VectorR\x03posB\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_dsp_proto_rawDescOnce sync.Once
	file_cmd_dsp_proto_rawDescData []byte
)

func file_cmd_dsp_proto_rawDescGZIP() []byte {
	file_cmd_dsp_proto_rawDescOnce.Do(func() {
		file_cmd_dsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_dsp_proto_rawDesc), len(file_cmd_dsp_proto_rawDesc)))
	})
	return file_cmd_dsp_proto_rawDescData
}

var file_cmd_dsp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cmd_dsp_proto_goTypes = []any{
	(*DspSyncBegin)(nil),         // 0: pb.DspSyncBegin
	(*DspSyncEnd)(nil),           // 1: pb.DspSyncEnd
	(*DspLoginFast)(nil),         // 2: pb.DspLoginFast
	(*DspLoginData)(nil),         // 3: pb.DspLoginData
	(*DspServerMaintain)(nil),    // 4: pb.DspServerMaintain
	(*DspKickRole)(nil),          // 5: pb.DspKickRole
	(*DspPreparedEnterZone)(nil), // 6: pb.DspPreparedEnterZone
	(*DspSyncMove)(nil),          // 7: pb.DspSyncMove
	(ESignInFastType_T)(0),       // 8: pb.ESignInFastType.T
	(*LoginData)(nil),            // 9: pb.LoginData
	(EKickType_T)(0),             // 10: pb.EKickType.T
	(*Vector)(nil),               // 11: pb.Vector
}
var file_cmd_dsp_proto_depIdxs = []int32{
	8,  // 0: pb.DspLoginFast.ty:type_name -> pb.ESignInFastType.T
	9,  // 1: pb.DspLoginData.data:type_name -> pb.LoginData
	10, // 2: pb.DspKickRole.ty:type_name -> pb.EKickType.T
	11, // 3: pb.DspSyncMove.pos:type_name -> pb.Vector
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cmd_dsp_proto_init() }
func file_cmd_dsp_proto_init() {
	if File_cmd_dsp_proto != nil {
		return
	}
	file_data_proto_init()
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_dsp_proto_rawDesc), len(file_cmd_dsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_dsp_proto_goTypes,
		DependencyIndexes: file_cmd_dsp_proto_depIdxs,
		MessageInfos:      file_cmd_dsp_proto_msgTypes,
	}.Build()
	File_cmd_dsp_proto = out.File
	file_cmd_dsp_proto_goTypes = nil
	file_cmd_dsp_proto_depIdxs = nil
}
