// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd_rsp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RspLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           EErrorCode_T           `protobuf:"varint,1,opt,name=err,proto3,enum=pb.EErrorCode_T" json:"err,omitempty"`
	Fast          bool                   `protobuf:"varint,2,opt,name=fast,proto3" json:"fast,omitempty"`                                       // 是否快速登陆
	RebootTime    int64                  `protobuf:"zigzag64,3,opt,name=reboot_time,json=rebootTime,proto3" json:"reboot_time,omitempty"`       // 预计开服时间戳，为 0 代表未知
	ShutdownTime  int64                  `protobuf:"zigzag64,4,opt,name=shutdown_time,json=shutdownTime,proto3" json:"shutdown_time,omitempty"` // 关服时间戳
	Devmod        bool                   `protobuf:"varint,5,opt,name=devmod,proto3" json:"devmod,omitempty"`                                   // 是否为开发模式
	Roles         []*RoleSummaryData     `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`                                      // 角色数组
	Account       string                 `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`                                  // 账号 id
	ServerTime    int64                  `protobuf:"zigzag64,8,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`       // 服务器时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspLogin) Reset() {
	*x = RspLogin{}
	mi := &file_cmd_rsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspLogin) ProtoMessage() {}

func (x *RspLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspLogin.ProtoReflect.Descriptor instead.
func (*RspLogin) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{0}
}

func (x *RspLogin) GetErr() EErrorCode_T {
	if x != nil {
		return x.Err
	}
	return EErrorCode_Ok
}

func (x *RspLogin) GetFast() bool {
	if x != nil {
		return x.Fast
	}
	return false
}

func (x *RspLogin) GetRebootTime() int64 {
	if x != nil {
		return x.RebootTime
	}
	return 0
}

func (x *RspLogin) GetShutdownTime() int64 {
	if x != nil {
		return x.ShutdownTime
	}
	return 0
}

func (x *RspLogin) GetDevmod() bool {
	if x != nil {
		return x.Devmod
	}
	return false
}

func (x *RspLogin) GetRoles() []*RoleSummaryData {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RspLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RspLogin) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type RspCreateRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           EErrorCode_T           `protobuf:"varint,1,opt,name=err,proto3,enum=pb.EErrorCode_T" json:"err,omitempty"`
	Role          *RoleSummaryData       `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // 角色
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspCreateRole) Reset() {
	*x = RspCreateRole{}
	mi := &file_cmd_rsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspCreateRole) ProtoMessage() {}

func (x *RspCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspCreateRole.ProtoReflect.Descriptor instead.
func (*RspCreateRole) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{1}
}

func (x *RspCreateRole) GetErr() EErrorCode_T {
	if x != nil {
		return x.Err
	}
	return EErrorCode_Ok
}

func (x *RspCreateRole) GetRole() *RoleSummaryData {
	if x != nil {
		return x.Role
	}
	return nil
}

type RspDeleteRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           EErrorCode_T           `protobuf:"varint,1,opt,name=err,proto3,enum=pb.EErrorCode_T" json:"err,omitempty"`
	RoleId        int64                  `protobuf:"zigzag64,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspDeleteRole) Reset() {
	*x = RspDeleteRole{}
	mi := &file_cmd_rsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspDeleteRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspDeleteRole) ProtoMessage() {}

func (x *RspDeleteRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspDeleteRole.ProtoReflect.Descriptor instead.
func (*RspDeleteRole) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{2}
}

func (x *RspDeleteRole) GetErr() EErrorCode_T {
	if x != nil {
		return x.Err
	}
	return EErrorCode_Ok
}

func (x *RspDeleteRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 角色进入游戏
type RspLoginRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           EErrorCode_T           `protobuf:"varint,1,opt,name=err,proto3,enum=pb.EErrorCode_T" json:"err,omitempty"`
	Data          *LoginData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 登录必要数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspLoginRole) Reset() {
	*x = RspLoginRole{}
	mi := &file_cmd_rsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspLoginRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspLoginRole) ProtoMessage() {}

func (x *RspLoginRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspLoginRole.ProtoReflect.Descriptor instead.
func (*RspLoginRole) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{3}
}

func (x *RspLoginRole) GetErr() EErrorCode_T {
	if x != nil {
		return x.Err
	}
	return EErrorCode_Ok
}

func (x *RspLoginRole) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 心跳
type RspPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspPing) Reset() {
	*x = RspPing{}
	mi := &file_cmd_rsp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPing) ProtoMessage() {}

func (x *RspPing) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPing.ProtoReflect.Descriptor instead.
func (*RspPing) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{4}
}

// 心跳(客户端切换后台发送该消息)
type RspPingXXX struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspPingXXX) Reset() {
	*x = RspPingXXX{}
	mi := &file_cmd_rsp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspPingXXX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPingXXX) ProtoMessage() {}

func (x *RspPingXXX) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPingXXX.ProtoReflect.Descriptor instead.
func (*RspPingXXX) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{5}
}

type RspEnterScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspEnterScene) Reset() {
	*x = RspEnterScene{}
	mi := &file_cmd_rsp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspEnterScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspEnterScene) ProtoMessage() {}

func (x *RspEnterScene) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspEnterScene.ProtoReflect.Descriptor instead.
func (*RspEnterScene) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{6}
}

type RspTestEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RspTestEnter) Reset() {
	*x = RspTestEnter{}
	mi := &file_cmd_rsp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RspTestEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspTestEnter) ProtoMessage() {}

func (x *RspTestEnter) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_rsp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspTestEnter.ProtoReflect.Descriptor instead.
func (*RspTestEnter) Descriptor() ([]byte, []int) {
	return file_cmd_rsp_proto_rawDescGZIP(), []int{7}
}

var File_cmd_rsp_proto protoreflect.FileDescriptor

const file_cmd_rsp_proto_rawDesc = "" +
	"\n" +
	"\rcmd_rsp.proto\x12\x02pb\x1a\n" +
	"data.proto\x1a\n" +
	"enum.proto\"\x86\x02\n" +
	"\bRspLogin\x12\"\n" +
	"\x03err\x18\x01 \x01(\x0e2\x10.pb.EErrorCode.TR\x03err\x12\x12\n" +
	"\x04fast\x18\x02 \x01(\bR\x04fast\x12\x1f\n" +
	"\vreboot_time\x18\x03 \x01(\x12R\n" +
	"rebootTime\x12#\n" +
	"\rshutdown_time\x18\x04 \x01(\x12R\fshutdownTime\x12\x16\n" +
	"\x06devmod\x18\x05 \x01(\bR\x06devmod\x12)\n" +
	"\x05roles\x18\x06 \x03(\v2\x13.pb.RoleSummaryDataR\x05roles\x12\x18\n" +
	"\aaccount\x18\a \x01(\tR\aaccount\x12\x1f\n" +
	"\vserver_time\x18\b \x01(\x12R\n" +
	"serverTime\"\\\n" +
	"\rRspCreateRole\x12\"\n" +
	"\x03err\x18\x01 \x01(\x0e2\x10.pb.EErrorCode.TR\x03err\x12'\n" +
	"\x04role\x18\x02 \x01(\v2\x13.pb.RoleSummaryDataR\x04role\"L\n" +
	"\rRspDeleteRole\x12\"\n" +
	"\x03err\x18\x01 \x01(\x0e2\x10.pb.EErrorCode.TR\x03err\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x12R\x06roleId\"U\n" +
	"\fRspLoginRole\x12\"\n" +
	"\x03err\x18\x01 \x01(\x0e2\x10.pb.EErrorCode.TR\x03err\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.pb.LoginDataR\x04data\"\t\n" +
	"\aRspPing\"\f\n" +
	"\n" +
	"RspPingXXX\"\x0f\n" +
	"\rRspEnterScene\"\x0e\n" +
	"\fRspTestEnterB\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_rsp_proto_rawDescOnce sync.Once
	file_cmd_rsp_proto_rawDescData []byte
)

func file_cmd_rsp_proto_rawDescGZIP() []byte {
	file_cmd_rsp_proto_rawDescOnce.Do(func() {
		file_cmd_rsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_rsp_proto_rawDesc), len(file_cmd_rsp_proto_rawDesc)))
	})
	return file_cmd_rsp_proto_rawDescData
}

var file_cmd_rsp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cmd_rsp_proto_goTypes = []any{
	(*RspLogin)(nil),        // 0: pb.RspLogin
	(*RspCreateRole)(nil),   // 1: pb.RspCreateRole
	(*RspDeleteRole)(nil),   // 2: pb.RspDeleteRole
	(*RspLoginRole)(nil),    // 3: pb.RspLoginRole
	(*RspPing)(nil),         // 4: pb.RspPing
	(*RspPingXXX)(nil),      // 5: pb.RspPingXXX
	(*RspEnterScene)(nil),   // 6: pb.RspEnterScene
	(*RspTestEnter)(nil),    // 7: pb.RspTestEnter
	(EErrorCode_T)(0),       // 8: pb.EErrorCode.T
	(*RoleSummaryData)(nil), // 9: pb.RoleSummaryData
	(*LoginData)(nil),       // 10: pb.LoginData
}
var file_cmd_rsp_proto_depIdxs = []int32{
	8,  // 0: pb.RspLogin.err:type_name -> pb.EErrorCode.T
	9,  // 1: pb.RspLogin.roles:type_name -> pb.RoleSummaryData
	8,  // 2: pb.RspCreateRole.err:type_name -> pb.EErrorCode.T
	9,  // 3: pb.RspCreateRole.role:type_name -> pb.RoleSummaryData
	8,  // 4: pb.RspDeleteRole.err:type_name -> pb.EErrorCode.T
	8,  // 5: pb.RspLoginRole.err:type_name -> pb.EErrorCode.T
	10, // 6: pb.RspLoginRole.data:type_name -> pb.LoginData
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cmd_rsp_proto_init() }
func file_cmd_rsp_proto_init() {
	if File_cmd_rsp_proto != nil {
		return
	}
	file_data_proto_init()
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_rsp_proto_rawDesc), len(file_cmd_rsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_rsp_proto_goTypes,
		DependencyIndexes: file_cmd_rsp_proto_depIdxs,
		MessageInfos:      file_cmd_rsp_proto_msgTypes,
	}.Build()
	File_cmd_rsp_proto = out.File
	file_cmd_rsp_proto_goTypes = nil
	file_cmd_rsp_proto_depIdxs = nil
}
