// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: cmd_req.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fast          bool                   `protobuf:"varint,1,opt,name=fast,proto3" json:"fast,omitempty"`                              // 是否快速登陆
	Magic         int64                  `protobuf:"zigzag64,2,opt,name=magic,proto3" json:"magic,omitempty"`                          // 魔数，快速登陆使用
	Timestamp     int64                  `protobuf:"zigzag64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // 当前时间
	SId           int64                  `protobuf:"zigzag64,4,opt,name=s_id,json=sId,proto3" json:"s_id,omitempty"`                   // 服务器 id
	RoleId        int64                  `protobuf:"zigzag64,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`          // 角色id，快速登陆使用
	Account       string                 `protobuf:"bytes,6,opt,name=account,proto3" json:"account,omitempty"`                         // uid
	Username      string                 `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`                       // sdk用户名
	ChannelId     string                 `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`    // 渠道
	ChannelUid    string                 `protobuf:"bytes,9,opt,name=channel_uid,json=channelUid,proto3" json:"channel_uid,omitempty"` // 渠道用户id
	Platform      string                 `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`                      // 平台
	Appid         string                 `protobuf:"bytes,11,opt,name=appid,proto3" json:"appid,omitempty"`                            // appid
	Token         string                 `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`                            // token
	Version       string                 `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`                        // 版本号
	Isadult       bool                   `protobuf:"varint,14,opt,name=isadult,proto3" json:"isadult,omitempty"`                       // 是否成年
	Iemi          string                 `protobuf:"bytes,15,opt,name=iemi,proto3" json:"iemi,omitempty"`                              // IMEI原始值
	Mac           string                 `protobuf:"bytes,16,opt,name=mac,proto3" json:"mac,omitempty"`                                // MAC原始值(转大写)
	Idfa          string                 `protobuf:"bytes,17,opt,name=idfa,proto3" json:"idfa,omitempty"`                              // IDFA原始值(IOS)
	Android       string                 `protobuf:"bytes,18,opt,name=android,proto3" json:"android,omitempty"`                        // Android原始值（Android)
	Dvbrand       string                 `protobuf:"bytes,19,opt,name=dvbrand,proto3" json:"dvbrand,omitempty"`                        // 设备品牌
	Dvtype        string                 `protobuf:"bytes,20,opt,name=dvtype,proto3" json:"dvtype,omitempty"`                          // 设备型号
	Ip            string                 `protobuf:"bytes,21,opt,name=ip,proto3" json:"ip,omitempty"`                                  // ip地址（客户端不用传）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_cmd_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{0}
}

func (x *ReqLogin) GetFast() bool {
	if x != nil {
		return x.Fast
	}
	return false
}

func (x *ReqLogin) GetMagic() int64 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *ReqLogin) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReqLogin) GetSId() int64 {
	if x != nil {
		return x.SId
	}
	return 0
}

func (x *ReqLogin) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ReqLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqLogin) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ReqLogin) GetChannelUid() string {
	if x != nil {
		return x.ChannelUid
	}
	return ""
}

func (x *ReqLogin) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ReqLogin) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *ReqLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReqLogin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReqLogin) GetIsadult() bool {
	if x != nil {
		return x.Isadult
	}
	return false
}

func (x *ReqLogin) GetIemi() string {
	if x != nil {
		return x.Iemi
	}
	return ""
}

func (x *ReqLogin) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *ReqLogin) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *ReqLogin) GetAndroid() string {
	if x != nil {
		return x.Android
	}
	return ""
}

func (x *ReqLogin) GetDvbrand() string {
	if x != nil {
		return x.Dvbrand
	}
	return ""
}

func (x *ReqLogin) GetDvtype() string {
	if x != nil {
		return x.Dvtype
	}
	return ""
}

func (x *ReqLogin) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ReqCreateRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           int64                  `protobuf:"zigzag64,1,opt,name=cid,proto3" json:"cid,omitempty"` // 要创建的配置cid
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  // 名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqCreateRole) Reset() {
	*x = ReqCreateRole{}
	mi := &file_cmd_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateRole) ProtoMessage() {}

func (x *ReqCreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateRole.ProtoReflect.Descriptor instead.
func (*ReqCreateRole) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{1}
}

func (x *ReqCreateRole) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ReqCreateRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReqDeleteRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"zigzag64,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqDeleteRole) Reset() {
	*x = ReqDeleteRole{}
	mi := &file_cmd_req_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqDeleteRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqDeleteRole) ProtoMessage() {}

func (x *ReqDeleteRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqDeleteRole.ProtoReflect.Descriptor instead.
func (*ReqDeleteRole) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{2}
}

func (x *ReqDeleteRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ReqLoginRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"zigzag64,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 要登录的角色id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLoginRole) Reset() {
	*x = ReqLoginRole{}
	mi := &file_cmd_req_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLoginRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginRole) ProtoMessage() {}

func (x *ReqLoginRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginRole.ProtoReflect.Descriptor instead.
func (*ReqLoginRole) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{3}
}

func (x *ReqLoginRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 心跳
type ReqPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPing) Reset() {
	*x = ReqPing{}
	mi := &file_cmd_req_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPing) ProtoMessage() {}

func (x *ReqPing) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPing.ProtoReflect.Descriptor instead.
func (*ReqPing) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{4}
}

// 心跳(客户端切换后台发送该消息)
type ReqPingXXX struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPingXXX) Reset() {
	*x = ReqPingXXX{}
	mi := &file_cmd_req_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPingXXX) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPingXXX) ProtoMessage() {}

func (x *ReqPingXXX) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPingXXX.ProtoReflect.Descriptor instead.
func (*ReqPingXXX) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{5}
}

type ReqEnterScene struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqEnterScene) Reset() {
	*x = ReqEnterScene{}
	mi := &file_cmd_req_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqEnterScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqEnterScene) ProtoMessage() {}

func (x *ReqEnterScene) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqEnterScene.ProtoReflect.Descriptor instead.
func (*ReqEnterScene) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{6}
}

type ReqTestEnter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqTestEnter) Reset() {
	*x = ReqTestEnter{}
	mi := &file_cmd_req_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqTestEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqTestEnter) ProtoMessage() {}

func (x *ReqTestEnter) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_req_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqTestEnter.ProtoReflect.Descriptor instead.
func (*ReqTestEnter) Descriptor() ([]byte, []int) {
	return file_cmd_req_proto_rawDescGZIP(), []int{7}
}

var File_cmd_req_proto protoreflect.FileDescriptor

const file_cmd_req_proto_rawDesc = "" +
	"\n" +
	"\rcmd_req.proto\x12\x02pb\"\x86\x04\n" +
	"\bReqLogin\x12\x12\n" +
	"\x04fast\x18\x01 \x01(\bR\x04fast\x12\x14\n" +
	"\x05magic\x18\x02 \x01(\x12R\x05magic\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x12R\ttimestamp\x12\x11\n" +
	"\x04s_id\x18\x04 \x01(\x12R\x03sId\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\x12R\x06roleId\x12\x18\n" +
	"\aaccount\x18\x06 \x01(\tR\aaccount\x12\x1a\n" +
	"\busername\x18\a \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"channel_id\x18\b \x01(\tR\tchannelId\x12\x1f\n" +
	"\vchannel_uid\x18\t \x01(\tR\n" +
	"channelUid\x12\x1a\n" +
	"\bplatform\x18\n" +
	" \x01(\tR\bplatform\x12\x14\n" +
	"\x05appid\x18\v \x01(\tR\x05appid\x12\x14\n" +
	"\x05token\x18\f \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\r \x01(\tR\aversion\x12\x18\n" +
	"\aisadult\x18\x0e \x01(\bR\aisadult\x12\x12\n" +
	"\x04iemi\x18\x0f \x01(\tR\x04iemi\x12\x10\n" +
	"\x03mac\x18\x10 \x01(\tR\x03mac\x12\x12\n" +
	"\x04idfa\x18\x11 \x01(\tR\x04idfa\x12\x18\n" +
	"\aandroid\x18\x12 \x01(\tR\aandroid\x12\x18\n" +
	"\advbrand\x18\x13 \x01(\tR\advbrand\x12\x16\n" +
	"\x06dvtype\x18\x14 \x01(\tR\x06dvtype\x12\x0e\n" +
	"\x02ip\x18\x15 \x01(\tR\x02ip\"5\n" +
	"\rReqCreateRole\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\x12R\x03cid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\rReqDeleteRole\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x12R\x06roleId\"'\n" +
	"\fReqLoginRole\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x12R\x06roleId\"\t\n" +
	"\aReqPing\"\f\n" +
	"\n" +
	"ReqPingXXX\"\x0f\n" +
	"\rReqEnterScene\"\x0e\n" +
	"\fReqTestEnterB\vZ\tserver/pbb\x06proto3"

var (
	file_cmd_req_proto_rawDescOnce sync.Once
	file_cmd_req_proto_rawDescData []byte
)

func file_cmd_req_proto_rawDescGZIP() []byte {
	file_cmd_req_proto_rawDescOnce.Do(func() {
		file_cmd_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_req_proto_rawDesc), len(file_cmd_req_proto_rawDesc)))
	})
	return file_cmd_req_proto_rawDescData
}

var file_cmd_req_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cmd_req_proto_goTypes = []any{
	(*ReqLogin)(nil),      // 0: pb.ReqLogin
	(*ReqCreateRole)(nil), // 1: pb.ReqCreateRole
	(*ReqDeleteRole)(nil), // 2: pb.ReqDeleteRole
	(*ReqLoginRole)(nil),  // 3: pb.ReqLoginRole
	(*ReqPing)(nil),       // 4: pb.ReqPing
	(*ReqPingXXX)(nil),    // 5: pb.ReqPingXXX
	(*ReqEnterScene)(nil), // 6: pb.ReqEnterScene
	(*ReqTestEnter)(nil),  // 7: pb.ReqTestEnter
}
var file_cmd_req_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_req_proto_init() }
func file_cmd_req_proto_init() {
	if File_cmd_req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_req_proto_rawDesc), len(file_cmd_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_req_proto_goTypes,
		DependencyIndexes: file_cmd_req_proto_depIdxs,
		MessageInfos:      file_cmd_req_proto_msgTypes,
	}.Build()
	File_cmd_req_proto = out.File
	file_cmd_req_proto_goTypes = nil
	file_cmd_req_proto_depIdxs = nil
}
