// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: data_srv.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单请求
type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                             // account_id
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`       // 商品 ID
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`  // 当前商品名称
	ProductDesc   string                 `protobuf:"bytes,4,opt,name=product_desc,json=productDesc,proto3" json:"product_desc,omitempty"`  // 当前商品描述
	BuyNum        int64                  `protobuf:"varint,5,opt,name=buy_num,json=buyNum,proto3" json:"buy_num,omitempty"`                // 购买数量
	Money         int64                  `protobuf:"varint,6,opt,name=money,proto3" json:"money,omitempty"`                                // 金额，传递单位为 分
	RoleId        int64                  `protobuf:"varint,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                // 玩家在游戏服中的角色ID
	RoleName      string                 `protobuf:"bytes,8,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`           // 玩家在游戏服中的角色名称
	RoleLevel     int64                  `protobuf:"varint,9,opt,name=role_level,json=roleLevel,proto3" json:"role_level,omitempty"`       // 玩家角色等级 必须为数字
	ServerId      int64                  `protobuf:"varint,10,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`         // 玩家所在的服务器ID
	ServerName    string                 `protobuf:"bytes,11,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`    // 玩家所在的服务器名称
	Extension     string                 `protobuf:"bytes,12,opt,name=extension,proto3" json:"extension,omitempty"`                        // 扩展参数
	Pid           string                 `protobuf:"bytes,13,opt,name=pid,proto3" json:"pid,omitempty"`                                    // 需要从SDK客户端获取 getCurrFlag
	Cip           string                 `protobuf:"bytes,14,opt,name=cip,proto3" json:"cip,omitempty"`                                    // 客户端ip地址
	CallbackUrl   string                 `protobuf:"bytes,15,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"` // 回调地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_data_srv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_data_srv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_data_srv_proto_rawDescGZIP(), []int{0}
}

func (x *OrderInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *OrderInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderInfo) GetProductDesc() string {
	if x != nil {
		return x.ProductDesc
	}
	return ""
}

func (x *OrderInfo) GetBuyNum() int64 {
	if x != nil {
		return x.BuyNum
	}
	return 0
}

func (x *OrderInfo) GetMoney() int64 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *OrderInfo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *OrderInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *OrderInfo) GetRoleLevel() int64 {
	if x != nil {
		return x.RoleLevel
	}
	return 0
}

func (x *OrderInfo) GetServerId() int64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *OrderInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *OrderInfo) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *OrderInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *OrderInfo) GetCip() string {
	if x != nil {
		return x.Cip
	}
	return ""
}

func (x *OrderInfo) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

var File_data_srv_proto protoreflect.FileDescriptor

const file_data_srv_proto_rawDesc = "" +
	"\n" +
	"\x0edata_srv.proto\x12\x02pb\"\xb1\x03\n" +
	"\tOrderInfo\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12!\n" +
	"\fproduct_desc\x18\x04 \x01(\tR\vproductDesc\x12\x17\n" +
	"\abuy_num\x18\x05 \x01(\x03R\x06buyNum\x12\x14\n" +
	"\x05money\x18\x06 \x01(\x03R\x05money\x12\x17\n" +
	"\arole_id\x18\a \x01(\x03R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\b \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"role_level\x18\t \x01(\x03R\troleLevel\x12\x1b\n" +
	"\tserver_id\x18\n" +
	" \x01(\x03R\bserverId\x12\x1f\n" +
	"\vserver_name\x18\v \x01(\tR\n" +
	"serverName\x12\x1c\n" +
	"\textension\x18\f \x01(\tR\textension\x12\x10\n" +
	"\x03pid\x18\r \x01(\tR\x03pid\x12\x10\n" +
	"\x03cip\x18\x0e \x01(\tR\x03cip\x12!\n" +
	"\fcallback_url\x18\x0f \x01(\tR\vcallbackUrlB\vZ\tserver/pbb\x06proto3"

var (
	file_data_srv_proto_rawDescOnce sync.Once
	file_data_srv_proto_rawDescData []byte
)

func file_data_srv_proto_rawDescGZIP() []byte {
	file_data_srv_proto_rawDescOnce.Do(func() {
		file_data_srv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_srv_proto_rawDesc), len(file_data_srv_proto_rawDesc)))
	})
	return file_data_srv_proto_rawDescData
}

var file_data_srv_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_data_srv_proto_goTypes = []any{
	(*OrderInfo)(nil), // 0: pb.OrderInfo
}
var file_data_srv_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_srv_proto_init() }
func file_data_srv_proto_init() {
	if File_data_srv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_srv_proto_rawDesc), len(file_data_srv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_srv_proto_goTypes,
		DependencyIndexes: file_data_srv_proto_depIdxs,
		MessageInfos:      file_data_srv_proto_msgTypes,
	}.Build()
	File_data_srv_proto = out.File
	file_data_srv_proto_goTypes = nil
	file_data_srv_proto_depIdxs = nil
}
