// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: data_fwd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FwdCheckDistance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkCid       int64                  `protobuf:"zigzag64,1,opt,name=mark_cid,json=markCid,proto3" json:"mark_cid,omitempty"`
	Arrive        bool                   `protobuf:"varint,2,opt,name=arrive,proto3" json:"arrive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FwdCheckDistance) Reset() {
	*x = FwdCheckDistance{}
	mi := &file_data_fwd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FwdCheckDistance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwdCheckDistance) ProtoMessage() {}

func (x *FwdCheckDistance) ProtoReflect() protoreflect.Message {
	mi := &file_data_fwd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwdCheckDistance.ProtoReflect.Descriptor instead.
func (*FwdCheckDistance) Descriptor() ([]byte, []int) {
	return file_data_fwd_proto_rawDescGZIP(), []int{0}
}

func (x *FwdCheckDistance) GetMarkCid() int64 {
	if x != nil {
		return x.MarkCid
	}
	return 0
}

func (x *FwdCheckDistance) GetArrive() bool {
	if x != nil {
		return x.Arrive
	}
	return false
}

type FwdNewOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FwdNewOrder) Reset() {
	*x = FwdNewOrder{}
	mi := &file_data_fwd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FwdNewOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwdNewOrder) ProtoMessage() {}

func (x *FwdNewOrder) ProtoReflect() protoreflect.Message {
	mi := &file_data_fwd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwdNewOrder.ProtoReflect.Descriptor instead.
func (*FwdNewOrder) Descriptor() ([]byte, []int) {
	return file_data_fwd_proto_rawDescGZIP(), []int{1}
}

type FwdKick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ty            EKickType_T            `protobuf:"varint,1,opt,name=ty,proto3,enum=pb.EKickType_T" json:"ty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FwdKick) Reset() {
	*x = FwdKick{}
	mi := &file_data_fwd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FwdKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FwdKick) ProtoMessage() {}

func (x *FwdKick) ProtoReflect() protoreflect.Message {
	mi := &file_data_fwd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FwdKick.ProtoReflect.Descriptor instead.
func (*FwdKick) Descriptor() ([]byte, []int) {
	return file_data_fwd_proto_rawDescGZIP(), []int{2}
}

func (x *FwdKick) GetTy() EKickType_T {
	if x != nil {
		return x.Ty
	}
	return EKickType_Invalid
}

var File_data_fwd_proto protoreflect.FileDescriptor

const file_data_fwd_proto_rawDesc = "" +
	"\n" +
	"\x0edata_fwd.proto\x12\x02pb\x1a\n" +
	"enum.proto\"E\n" +
	"\x10FwdCheckDistance\x12\x19\n" +
	"\bmark_cid\x18\x01 \x01(\x12R\amarkCid\x12\x16\n" +
	"\x06arrive\x18\x02 \x01(\bR\x06arrive\"\r\n" +
	"\vFwdNewOrder\"*\n" +
	"\aFwdKick\x12\x1f\n" +
	"\x02ty\x18\x01 \x01(\x0e2\x0f.pb.EKickType.TR\x02tyB\vZ\tserver/pbb\x06proto3"

var (
	file_data_fwd_proto_rawDescOnce sync.Once
	file_data_fwd_proto_rawDescData []byte
)

func file_data_fwd_proto_rawDescGZIP() []byte {
	file_data_fwd_proto_rawDescOnce.Do(func() {
		file_data_fwd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_fwd_proto_rawDesc), len(file_data_fwd_proto_rawDesc)))
	})
	return file_data_fwd_proto_rawDescData
}

var file_data_fwd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_fwd_proto_goTypes = []any{
	(*FwdCheckDistance)(nil), // 0: pb.FwdCheckDistance
	(*FwdNewOrder)(nil),      // 1: pb.FwdNewOrder
	(*FwdKick)(nil),          // 2: pb.FwdKick
	(EKickType_T)(0),         // 3: pb.EKickType.T
}
var file_data_fwd_proto_depIdxs = []int32{
	3, // 0: pb.FwdKick.ty:type_name -> pb.EKickType.T
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_fwd_proto_init() }
func file_data_fwd_proto_init() {
	if File_data_fwd_proto != nil {
		return
	}
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_fwd_proto_rawDesc), len(file_data_fwd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_fwd_proto_goTypes,
		DependencyIndexes: file_data_fwd_proto_depIdxs,
		MessageInfos:      file_data_fwd_proto_msgTypes,
	}.Build()
	File_data_fwd_proto = out.File
	file_data_fwd_proto_goTypes = nil
	file_data_fwd_proto_depIdxs = nil
}
