// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EErrorCode_T int32

const (
	EErrorCode_Ok                     EErrorCode_T = 0 // 成功
	EErrorCode_Failed                 EErrorCode_T = 1 // 通用服务器错误
	EErrorCode_ServerNotFound         EErrorCode_T = 3
	EErrorCode_RoleIllegal            EErrorCode_T = 5
	EErrorCode_PlayerRoleForbid       EErrorCode_T = 6
	EErrorCode_RoleSignInTimeout      EErrorCode_T = 7
	EErrorCode_RoleInvalidCid         EErrorCode_T = 8
	EErrorCode_RoleNameIllegal        EErrorCode_T = 9
	EErrorCode_RoleDuplicate          EErrorCode_T = 10
	EErrorCode_RoleNameLen            EErrorCode_T = 11
	EErrorCode_RoleNewTimeout         EErrorCode_T = 12
	EErrorCode_RoleHasDeleted         EErrorCode_T = 13
	EErrorCode_RoleDelTimeout         EErrorCode_T = 14
	EErrorCode_RoleNumLimit           EErrorCode_T = 15
	EErrorCode_RoleNotFound           EErrorCode_T = 16
	EErrorCode_ServerMaintain         EErrorCode_T = 17
	EErrorCode_ServerBusy             EErrorCode_T = 18
	EErrorCode_PlayerSignInTimeout    EErrorCode_T = 19
	EErrorCode_PlayerTokenTimeOut     EErrorCode_T = 21
	EErrorCode_PlayerTokenInvalid     EErrorCode_T = 22
	EErrorCode_PlayerTokenAlreadyUsed EErrorCode_T = 23
	EErrorCode_PlayerVersionError     EErrorCode_T = 24
)

// Enum value maps for EErrorCode_T.
var (
	EErrorCode_T_name = map[int32]string{
		0:  "Ok",
		1:  "Failed",
		3:  "ServerNotFound",
		5:  "RoleIllegal",
		6:  "PlayerRoleForbid",
		7:  "RoleSignInTimeout",
		8:  "RoleInvalidCid",
		9:  "RoleNameIllegal",
		10: "RoleDuplicate",
		11: "RoleNameLen",
		12: "RoleNewTimeout",
		13: "RoleHasDeleted",
		14: "RoleDelTimeout",
		15: "RoleNumLimit",
		16: "RoleNotFound",
		17: "ServerMaintain",
		18: "ServerBusy",
		19: "PlayerSignInTimeout",
		21: "PlayerTokenTimeOut",
		22: "PlayerTokenInvalid",
		23: "PlayerTokenAlreadyUsed",
		24: "PlayerVersionError",
	}
	EErrorCode_T_value = map[string]int32{
		"Ok":                     0,
		"Failed":                 1,
		"ServerNotFound":         3,
		"RoleIllegal":            5,
		"PlayerRoleForbid":       6,
		"RoleSignInTimeout":      7,
		"RoleInvalidCid":         8,
		"RoleNameIllegal":        9,
		"RoleDuplicate":          10,
		"RoleNameLen":            11,
		"RoleNewTimeout":         12,
		"RoleHasDeleted":         13,
		"RoleDelTimeout":         14,
		"RoleNumLimit":           15,
		"RoleNotFound":           16,
		"ServerMaintain":         17,
		"ServerBusy":             18,
		"PlayerSignInTimeout":    19,
		"PlayerTokenTimeOut":     21,
		"PlayerTokenInvalid":     22,
		"PlayerTokenAlreadyUsed": 23,
		"PlayerVersionError":     24,
	}
)

func (x EErrorCode_T) Enum() *EErrorCode_T {
	p := new(EErrorCode_T)
	*p = x
	return p
}

func (x EErrorCode_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EErrorCode_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (EErrorCode_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x EErrorCode_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EErrorCode_T.Descriptor instead.
func (EErrorCode_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0, 0}
}

type EKickType_T int32

const (
	EKickType_Invalid          EKickType_T = 0  // 未知，关闭连接
	EKickType_OtherLogin       EKickType_T = 1  // 账号在其他地方登录，关闭连接
	EKickType_GMKick           EKickType_T = 2  // GM 强制下线，关闭连接
	EKickType_ServerShutdown   EKickType_T = 3  // 服务器关闭，关闭连接
	EKickType_Young            EKickType_T = 6  // 防沉迷踢人下线，关闭连接
	EKickType_Disconnect       EKickType_T = 7  // 心跳断开或消息满，关闭连接
	EKickType_MessageOverflow  EKickType_T = 8  // 每秒消息超过服务器允许上限，关闭连接
	EKickType_InternalError    EKickType_T = 10 // 内部错误，关闭连接
	EKickType_SceneLoadMax     EKickType_T = 12 // 场景负载满，关闭连接
	EKickType_SceneEnterFailed EKickType_T = 13 // 进入场景时客户端发送了过多的消息，不断连接
)

// Enum value maps for EKickType_T.
var (
	EKickType_T_name = map[int32]string{
		0:  "Invalid",
		1:  "OtherLogin",
		2:  "GMKick",
		3:  "ServerShutdown",
		6:  "Young",
		7:  "Disconnect",
		8:  "MessageOverflow",
		10: "InternalError",
		12: "SceneLoadMax",
		13: "SceneEnterFailed",
	}
	EKickType_T_value = map[string]int32{
		"Invalid":          0,
		"OtherLogin":       1,
		"GMKick":           2,
		"ServerShutdown":   3,
		"Young":            6,
		"Disconnect":       7,
		"MessageOverflow":  8,
		"InternalError":    10,
		"SceneLoadMax":     12,
		"SceneEnterFailed": 13,
	}
)

func (x EKickType_T) Enum() *EKickType_T {
	p := new(EKickType_T)
	*p = x
	return p
}

func (x EKickType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EKickType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (EKickType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x EKickType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EKickType_T.Descriptor instead.
func (EKickType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1, 0}
}

type ERoleType_T int32

const (
	ERoleType_Normal ERoleType_T = 0 //普通玩家
	ERoleType_GM     ERoleType_T = 1 // GM
)

// Enum value maps for ERoleType_T.
var (
	ERoleType_T_name = map[int32]string{
		0: "Normal",
		1: "GM",
	}
	ERoleType_T_value = map[string]int32{
		"Normal": 0,
		"GM":     1,
	}
)

func (x ERoleType_T) Enum() *ERoleType_T {
	p := new(ERoleType_T)
	*p = x
	return p
}

func (x ERoleType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERoleType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[2].Descriptor()
}

func (ERoleType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[2]
}

func (x ERoleType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERoleType_T.Descriptor instead.
func (ERoleType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2, 0}
}

type EForbiddenType_T int32

const (
	EForbiddenType_Invalid EForbiddenType_T = 0 //占位
	EForbiddenType_Chat    EForbiddenType_T = 1 //禁言
	EForbiddenType_Account EForbiddenType_T = 2 //封号
	EForbiddenType_Undo    EForbiddenType_T = 3 //解封
	EForbiddenType_Mac     EForbiddenType_T = 4 //根据mac封号
	EForbiddenType_IP      EForbiddenType_T = 5 //根据ip封号
)

// Enum value maps for EForbiddenType_T.
var (
	EForbiddenType_T_name = map[int32]string{
		0: "Invalid",
		1: "Chat",
		2: "Account",
		3: "Undo",
		4: "Mac",
		5: "IP",
	}
	EForbiddenType_T_value = map[string]int32{
		"Invalid": 0,
		"Chat":    1,
		"Account": 2,
		"Undo":    3,
		"Mac":     4,
		"IP":      5,
	}
)

func (x EForbiddenType_T) Enum() *EForbiddenType_T {
	p := new(EForbiddenType_T)
	*p = x
	return p
}

func (x EForbiddenType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EForbiddenType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[3].Descriptor()
}

func (EForbiddenType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[3]
}

func (x EForbiddenType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EForbiddenType_T.Descriptor instead.
func (EForbiddenType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{3, 0}
}

type EObjType_T int32

const (
	EObjType_None EObjType_T = 0 // 无
	EObjType_Item EObjType_T = 1 // 道具
)

// Enum value maps for EObjType_T.
var (
	EObjType_T_name = map[int32]string{
		0: "None",
		1: "Item",
	}
	EObjType_T_value = map[string]int32{
		"None": 0,
		"Item": 1,
	}
)

func (x EObjType_T) Enum() *EObjType_T {
	p := new(EObjType_T)
	*p = x
	return p
}

func (x EObjType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EObjType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[4].Descriptor()
}

func (EObjType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[4]
}

func (x EObjType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EObjType_T.Descriptor instead.
func (EObjType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{4, 0}
}

type ESignInFastType_T int32

const (
	ESignInFastType_Invalid ESignInFastType_T = 0 // 无效
	ESignInFastType_Player  ESignInFastType_T = 1 // 账号登录
	ESignInFastType_Role    ESignInFastType_T = 2 // 角色登录
)

// Enum value maps for ESignInFastType_T.
var (
	ESignInFastType_T_name = map[int32]string{
		0: "Invalid",
		1: "Player",
		2: "Role",
	}
	ESignInFastType_T_value = map[string]int32{
		"Invalid": 0,
		"Player":  1,
		"Role":    2,
	}
)

func (x ESignInFastType_T) Enum() *ESignInFastType_T {
	p := new(ESignInFastType_T)
	*p = x
	return p
}

func (x ESignInFastType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESignInFastType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[5].Descriptor()
}

func (ESignInFastType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[5]
}

func (x ESignInFastType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESignInFastType_T.Descriptor instead.
func (ESignInFastType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{5, 0}
}

type ECondType_T int32

const (
	ECondType_Invalid  ECondType_T = 0
	ECondType_LoginDay ECondType_T = 1 // 累计上线天数(condtype = 2)
)

// Enum value maps for ECondType_T.
var (
	ECondType_T_name = map[int32]string{
		0: "Invalid",
		1: "LoginDay",
	}
	ECondType_T_value = map[string]int32{
		"Invalid":  0,
		"LoginDay": 1,
	}
)

func (x ECondType_T) Enum() *ECondType_T {
	p := new(ECondType_T)
	*p = x
	return p
}

func (x ECondType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ECondType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[6].Descriptor()
}

func (ECondType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[6]
}

func (x ECondType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ECondType_T.Descriptor instead.
func (ECondType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{6, 0}
}

type EAttrType_T int32

const (
	EAttrType_Invalid EAttrType_T = 0
)

// Enum value maps for EAttrType_T.
var (
	EAttrType_T_name = map[int32]string{
		0: "Invalid",
	}
	EAttrType_T_value = map[string]int32{
		"Invalid": 0,
	}
)

func (x EAttrType_T) Enum() *EAttrType_T {
	p := new(EAttrType_T)
	*p = x
	return p
}

func (x EAttrType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EAttrType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[7].Descriptor()
}

func (EAttrType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[7]
}

func (x EAttrType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EAttrType_T.Descriptor instead.
func (EAttrType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{7, 0}
}

type EEntityType_T int32

const (
	EEntityType_None    EEntityType_T = 0    // 无效的实体类型
	EEntityType_Role    EEntityType_T = 1    // 角色
	EEntityType_Npc     EEntityType_T = 2    // NPC
	EEntityType_Bullet  EEntityType_T = 4    // 子弹
	EEntityType_Monster EEntityType_T = 8    // 怪
	EEntityType_Max     EEntityType_T = 8191 // 全部
)

// Enum value maps for EEntityType_T.
var (
	EEntityType_T_name = map[int32]string{
		0:    "None",
		1:    "Role",
		2:    "Npc",
		4:    "Bullet",
		8:    "Monster",
		8191: "Max",
	}
	EEntityType_T_value = map[string]int32{
		"None":    0,
		"Role":    1,
		"Npc":     2,
		"Bullet":  4,
		"Monster": 8,
		"Max":     8191,
	}
)

func (x EEntityType_T) Enum() *EEntityType_T {
	p := new(EEntityType_T)
	*p = x
	return p
}

func (x EEntityType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EEntityType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[8].Descriptor()
}

func (EEntityType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[8]
}

func (x EEntityType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EEntityType_T.Descriptor instead.
func (EEntityType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{8, 0}
}

type ESceneType_T int32

const (
	ESceneType_Login   ESceneType_T = 0 // 登录场景
	ESceneType_Role    ESceneType_T = 1 // 选角场景
	ESceneType_MapBase ESceneType_T = 2 // 地图基础场景
	ESceneType_Main    ESceneType_T = 3 // 主场景
)

// Enum value maps for ESceneType_T.
var (
	ESceneType_T_name = map[int32]string{
		0: "Login",
		1: "Role",
		2: "MapBase",
		3: "Main",
	}
	ESceneType_T_value = map[string]int32{
		"Login":   0,
		"Role":    1,
		"MapBase": 2,
		"Main":    3,
	}
)

func (x ESceneType_T) Enum() *ESceneType_T {
	p := new(ESceneType_T)
	*p = x
	return p
}

func (x ESceneType_T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ESceneType_T) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[9].Descriptor()
}

func (ESceneType_T) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[9]
}

func (x ESceneType_T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ESceneType_T.Descriptor instead.
func (ESceneType_T) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{9, 0}
}

// 统一返回状态
type EErrorCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EErrorCode) Reset() {
	*x = EErrorCode{}
	mi := &file_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EErrorCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EErrorCode) ProtoMessage() {}

func (x *EErrorCode) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EErrorCode.ProtoReflect.Descriptor instead.
func (*EErrorCode) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

// 提下线类型
type EKickType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EKickType) Reset() {
	*x = EKickType{}
	mi := &file_enum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EKickType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EKickType) ProtoMessage() {}

func (x *EKickType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EKickType.ProtoReflect.Descriptor instead.
func (*EKickType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

type ERoleType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ERoleType) Reset() {
	*x = ERoleType{}
	mi := &file_enum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ERoleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ERoleType) ProtoMessage() {}

func (x *ERoleType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ERoleType.ProtoReflect.Descriptor instead.
func (*ERoleType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2}
}

type EForbiddenType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EForbiddenType) Reset() {
	*x = EForbiddenType{}
	mi := &file_enum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EForbiddenType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EForbiddenType) ProtoMessage() {}

func (x *EForbiddenType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EForbiddenType.ProtoReflect.Descriptor instead.
func (*EForbiddenType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{3}
}

type EObjType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EObjType) Reset() {
	*x = EObjType{}
	mi := &file_enum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EObjType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EObjType) ProtoMessage() {}

func (x *EObjType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EObjType.ProtoReflect.Descriptor instead.
func (*EObjType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{4}
}

// 重登类型
type ESignInFastType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ESignInFastType) Reset() {
	*x = ESignInFastType{}
	mi := &file_enum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ESignInFastType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESignInFastType) ProtoMessage() {}

func (x *ESignInFastType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESignInFastType.ProtoReflect.Descriptor instead.
func (*ESignInFastType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{5}
}

type ECondType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECondType) Reset() {
	*x = ECondType{}
	mi := &file_enum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECondType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECondType) ProtoMessage() {}

func (x *ECondType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECondType.ProtoReflect.Descriptor instead.
func (*ECondType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{6}
}

type EAttrType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAttrType) Reset() {
	*x = EAttrType{}
	mi := &file_enum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAttrType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAttrType) ProtoMessage() {}

func (x *EAttrType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAttrType.ProtoReflect.Descriptor instead.
func (*EAttrType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{7}
}

type EEntityType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EEntityType) Reset() {
	*x = EEntityType{}
	mi := &file_enum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EEntityType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EEntityType) ProtoMessage() {}

func (x *EEntityType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EEntityType.ProtoReflect.Descriptor instead.
func (*EEntityType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{8}
}

type ESceneType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ESceneType) Reset() {
	*x = ESceneType{}
	mi := &file_enum_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ESceneType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ESceneType) ProtoMessage() {}

func (x *ESceneType) ProtoReflect() protoreflect.Message {
	mi := &file_enum_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ESceneType.ProtoReflect.Descriptor instead.
func (*ESceneType) Descriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{9}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto\x12\x02pb\"\xc6\x03\n" +
	"\n" +
	"EErrorCode\"\xb7\x03\n" +
	"\x01T\x12\x06\n" +
	"\x02Ok\x10\x00\x12\n" +
	"\n" +
	"\x06Failed\x10\x01\x12\x12\n" +
	"\x0eServerNotFound\x10\x03\x12\x0f\n" +
	"\vRoleIllegal\x10\x05\x12\x14\n" +
	"\x10PlayerRoleForbid\x10\x06\x12\x15\n" +
	"\x11RoleSignInTimeout\x10\a\x12\x12\n" +
	"\x0eRoleInvalidCid\x10\b\x12\x13\n" +
	"\x0fRoleNameIllegal\x10\t\x12\x11\n" +
	"\rRoleDuplicate\x10\n" +
	"\x12\x0f\n" +
	"\vRoleNameLen\x10\v\x12\x12\n" +
	"\x0eRoleNewTimeout\x10\f\x12\x12\n" +
	"\x0eRoleHasDeleted\x10\r\x12\x12\n" +
	"\x0eRoleDelTimeout\x10\x0e\x12\x10\n" +
	"\fRoleNumLimit\x10\x0f\x12\x10\n" +
	"\fRoleNotFound\x10\x10\x12\x12\n" +
	"\x0eServerMaintain\x10\x11\x12\x0e\n" +
	"\n" +
	"ServerBusy\x10\x12\x12\x17\n" +
	"\x13PlayerSignInTimeout\x10\x13\x12\x16\n" +
	"\x12PlayerTokenTimeOut\x10\x15\x12\x16\n" +
	"\x12PlayerTokenInvalid\x10\x16\x12\x1a\n" +
	"\x16PlayerTokenAlreadyUsed\x10\x17\x12\x16\n" +
	"\x12PlayerVersionError\x10\x18\"\xb9\x01\n" +
	"\tEKickType\"\xab\x01\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\x12\x0e\n" +
	"\n" +
	"OtherLogin\x10\x01\x12\n" +
	"\n" +
	"\x06GMKick\x10\x02\x12\x12\n" +
	"\x0eServerShutdown\x10\x03\x12\t\n" +
	"\x05Young\x10\x06\x12\x0e\n" +
	"\n" +
	"Disconnect\x10\a\x12\x13\n" +
	"\x0fMessageOverflow\x10\b\x12\x11\n" +
	"\rInternalError\x10\n" +
	"\x12\x10\n" +
	"\fSceneLoadMax\x10\f\x12\x14\n" +
	"\x10SceneEnterFailed\x10\r\"$\n" +
	"\tERoleType\"\x17\n" +
	"\x01T\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\x06\n" +
	"\x02GM\x10\x01\"T\n" +
	"\x0eEForbiddenType\"B\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\x12\b\n" +
	"\x04Chat\x10\x01\x12\v\n" +
	"\aAccount\x10\x02\x12\b\n" +
	"\x04Undo\x10\x03\x12\a\n" +
	"\x03Mac\x10\x04\x12\x06\n" +
	"\x02IP\x10\x05\"#\n" +
	"\bEObjType\"\x17\n" +
	"\x01T\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04Item\x10\x01\"9\n" +
	"\x0fESignInFastType\"&\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\x12\n" +
	"\n" +
	"\x06Player\x10\x01\x12\b\n" +
	"\x04Role\x10\x02\"+\n" +
	"\tECondType\"\x1e\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\x12\f\n" +
	"\bLoginDay\x10\x01\"\x1d\n" +
	"\tEAttrType\"\x10\n" +
	"\x01T\x12\v\n" +
	"\aInvalid\x10\x00\"R\n" +
	"\vEEntityType\"C\n" +
	"\x01T\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04Role\x10\x01\x12\a\n" +
	"\x03Npc\x10\x02\x12\n" +
	"\n" +
	"\x06Bullet\x10\x04\x12\v\n" +
	"\aMonster\x10\b\x12\b\n" +
	"\x03Max\x10\xff?\"=\n" +
	"\n" +
	"ESceneType\"/\n" +
	"\x01T\x12\t\n" +
	"\x05Login\x10\x00\x12\b\n" +
	"\x04Role\x10\x01\x12\v\n" +
	"\aMapBase\x10\x02\x12\b\n" +
	"\x04Main\x10\x03B\vZ\tserver/pbb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_enum_proto_goTypes = []any{
	(EErrorCode_T)(0),       // 0: pb.EErrorCode.T
	(EKickType_T)(0),        // 1: pb.EKickType.T
	(ERoleType_T)(0),        // 2: pb.ERoleType.T
	(EForbiddenType_T)(0),   // 3: pb.EForbiddenType.T
	(EObjType_T)(0),         // 4: pb.EObjType.T
	(ESignInFastType_T)(0),  // 5: pb.ESignInFastType.T
	(ECondType_T)(0),        // 6: pb.ECondType.T
	(EAttrType_T)(0),        // 7: pb.EAttrType.T
	(EEntityType_T)(0),      // 8: pb.EEntityType.T
	(ESceneType_T)(0),       // 9: pb.ESceneType.T
	(*EErrorCode)(nil),      // 10: pb.EErrorCode
	(*EKickType)(nil),       // 11: pb.EKickType
	(*ERoleType)(nil),       // 12: pb.ERoleType
	(*EForbiddenType)(nil),  // 13: pb.EForbiddenType
	(*EObjType)(nil),        // 14: pb.EObjType
	(*ESignInFastType)(nil), // 15: pb.ESignInFastType
	(*ECondType)(nil),       // 16: pb.ECondType
	(*EAttrType)(nil),       // 17: pb.EAttrType
	(*EEntityType)(nil),     // 18: pb.EEntityType
	(*ESceneType)(nil),      // 19: pb.ESceneType
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
		MessageInfos:      file_enum_proto_msgTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
